# The following environment variables are substituted if present
# * QUORUM_CONSENSUS: default to istanbul
# * QUORUM_DOCKER_IMAGE: default to quorumengineering/quorum:21.7.1
# * QUORUM_TX_MANAGER_DOCKER_IMAGE: default to quorumengineering/tessera:21.7.2
# * QUORUM_GETH_ARGS: extra geth arguments to be included when running geth
# To use Constellation, set QUORUM_TX_MANAGER_DOCKER_IMAGE to Constellation docker image,
# e.g.: QUORUM_TX_MANAGER_DOCKER_IMAGE=quorumengineering/constellation:0.3.2 docker-compose up -d
# To use Remix, set QUORUM_GETH_ARGS="--rpccorsdomain https://remix.ethereum.org"
version: "3.6"
services:
  mariadb:
    image: mariadb:10.7
    hostname: mariadb
    ports:
      - 3301:3301
    volumes:
      - ./mariadb:/var/lib/mysql:rw
      - ./runSQL:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=tesseradbuser
      - MYSQL_DATABASE=tessera
      - MYSQL_TCP_PORT=3301
    expose:
      - 3301
    networks:
      mariadb-net:
        ipv4_address: 172.16.238.41
networks:
  mariadb-net:
    name: mariadb-net
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24